name: Push
on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm test

  build:
    name: Build ${{ matrix.build_target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_target:
          - chromium
          - firefox
          - web
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build:${{ matrix.build_target }}
        env:
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
          UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tabliss-${{ matrix.build_target }}
          path: dist/${{ matrix.build_target }}

      - name: Commit and Push to artifact_builds Branch
        run: |
          git checkout artifact_builds || git checkout -b artifact_builds
          git add -f dist/${{ matrix.build_target }}  # Force add ignored files
          git commit -m "Updated for: ${{ github.event.head_commit.message }}"
          git push origin artifact_builds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
