name: CI/CD

on: push

permissions:
  contents: read
  pages: write
  id-token: write  # This is required for deploy-pages to work

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm test

  build:
    name: Build ${{ matrix.build_target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_target:
          - chromium
          - firefox
          - web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build:${{ matrix.build_target }}
        env:
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
          UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          name: tabliss-${{ matrix.build_target }}
          path: dist/${{ matrix.build_target }}

  deploy:
    name: Deploy Web Version to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Web Artifact
        uses: actions/download-artifact@v4
        with:
          name: tabliss-web
          path: dist  # This extracts the artifact as a folder, not a ZIP file

      - name: List downloaded files (debug)
        run: ls -R dist  # Check what's inside `dist/`

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Web Version to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist  # Deploys the contents of `dist/`

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v3


